/* comment */
#ifndef INCLUDED_VCL_INC_VCLPLUGINAPI_H
#define INCLUDED_VCL_INC_VCLPLUGINAPI_H

#include <sal/config.h>
#include <sal/types.h>

#if defined VCLPLUG_GEN_IMPLEMENTATION
#define VCLPLUG_GEN_PUBLIC SAL_DLLPUBLIC_EXPORT
#else
#define VCLPLUG_GEN_PUBLIC SAL_DLLPUBLIC_IMPORT
#endif

#if defined VCLPLUG_GTK_IMPLEMENTATION
#define VCLPLUG_GTK_PUBLIC SAL_DLLPUBLIC_EXPORT
#else
#define VCLPLUG_GTK_PUBLIC SAL_DLLPUBLIC_IMPORT
#endif

#if defined VCLPLUG_KF5_IMPLEMENTATION
#define VCLPLUG_KF5_PUBLIC SAL_DLLPUBLIC_EXPORT
#else
#define VCLPLUG_KF5_PUBLIC SAL_DLLPUBLIC_IMPORT
#endif

#if defined VCLPLUG_OSX_IMPLEMENTATION
#define VCLPLUG_OSX_PUBLIC SAL_DLLPUBLIC_EXPORT
#else
#define VCLPLUG_OSX_PUBLIC SAL_DLLPUBLIC_IMPORT
#endif

#if defined VCLPLUG_QT_IMPLEMENTATION
#define VCLPLUG_QT_PUBLIC SAL_DLLPUBLIC_EXPORT
#else
#define VCLPLUG_QT_PUBLIC SAL_DLLPUBLIC_IMPORT
#endif

#if defined VCLPLUG_SVP_IMPLEMENTATION
#define VCLPLUG_SVP_PUBLIC SAL_DLLPUBLIC_EXPORT
#else
#define VCLPLUG_SVP_PUBLIC SAL_DLLPUBLIC_IMPORT
#endif

#if defined VCLPLUG_WIN_IMPLEMENTATION
#define VCLPLUG_WIN_PUBLIC SAL_DLLPUBLIC_EXPORT
#else
#define VCLPLUG_WIN_PUBLIC SAL_DLLPUBLIC_IMPORT
#endif

#if defined DESKTOP_DETECTOR_IMPLEMENTATION
#define DESKTOP_DETECTOR_PUBLIC SAL_DLLPUBLIC_EXPORT
#else
#define DESKTOP_DETECTOR_PUBLIC SAL_DLLPUBLIC_IMPORT
#endif

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
